name: build-and-push

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'     # 每周一自动重建
  workflow_dispatch:        # 手动触发

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4            # 拉代码
      - name: Log in to GHCR
        uses: docker/login-action@v3         # 登录注册表
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build & push
        uses: docker/build-push-action@v5    # 构建并推送镜像
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}